version: '3'

services:
  hey-car-app-container:
    image: hey-car-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/hey-car-app
    ports:
      - "8081:8080"
