spring:
  application:
    name: hey-car
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/user/.h2/hey-car
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format-sql: true
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas:
      - PUBLIC

jwt:
  secret:javainuse
spring.jpa.properties.hibernate.default_schema: public
hibernate:
  dialect: org.hibernate.dialect.H2Dialect